### ISSUE TITLE
Illegal YAML and command/permission

### ISSUE THREAD

**Issue by SlimeDog** [flinbein/PowerNBT#39]
PowerNBP 2.8

I'm not sure what's going on here.

plugin.yml
```
name: PowerNBT
description: Powerful nbt editor for bukkit
author: DPOH-VAR
main: me.dpohvar.powernbt.PowerNBT
website: https://github.com/flinbein/powernbt
version: 1.0.2
softdepend:
    - VarScript
commands:
    powernbt:
        description: use nbt commands
        usage: /nbt ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt
            - nbt
    powernbt.:
        description: use nbt commands (silent mode)
        usage: /nbt. ... use [Tab] key for help
        permission: powernbt.use
        aliases:
            - pnbt.
            - nbt.
```

[AntiMalware] [07:17:08] [SEVERE]: Failed to set config section Key: powernbt. Value: {description=use nbt commands (silent mode), usage=/nbt. ... use [Tab] key for help, permission=powernbt.use, aliases=[pnbt., nbt.]}

Also -- perhaps as a consequence -- LuckPerms does not tab-complete the permissions nodes. Are they registered?
